/* eslint-disable @typescript-eslint/no-explicit-any */
// THIS FILE IS AUTO-GENERATED. DO NOT EDIT MANUALLY.
// Generated by prismagen

import { prisma } from "@/prisma/prisma";
import { IsAuthenticatedAdmin } from "@/auth/AuthFunctions";
import { DiscountCode_GetAll } from "@/prisma/functions/DiscountCode/DiscountCodeFun";

function pickAllowed(obj: Record<string, any>, allowed: string[]) {
  const set = new Set(allowed);
  const out: Record<string, any> = {};
  for (const [k, v] of Object.entries(obj ?? {})) {
    if (set.has(k)) out[k] = v;
  }
  return out;
}

const ALLOWED_FIELDS = ["code","description","discountPct","validFrom","validTo","numberOfUses","limitUses","isActive"] as const;

export async function GET() {
  const data = await DiscountCode_GetAll();
  return new Response(JSON.stringify(data), { status: 200 });
}

export async function POST(request: Request) {
  const user = await IsAuthenticatedAdmin();
  if (!user) return new Response("Unauthorized", { status: 401 });

  const body = await request.json();
  const data = pickAllowed(body, [...ALLOWED_FIELDS]);
  const created = await prisma.discountCode.create({ data: data as any });
  return new Response(JSON.stringify(created), { status: 201 });
}

export async function PUT(request: Request) {
  const user = await IsAuthenticatedAdmin();
  if (!user) return new Response("Unauthorized", { status: 401 });

  const body = await request.json();
  const id = body?.id;
  if (!id) return new Response("Missing id", { status: 400 });
  const data = pickAllowed(body, [...ALLOWED_FIELDS]);
  const updated = await prisma.discountCode.update({ where: { id } as any, data: data as any });
  return new Response(JSON.stringify(updated), { status: 200 });
}

export async function DELETE(request: Request) {
  const user = await IsAuthenticatedAdmin();
  if (!user) return new Response("Unauthorized", { status: 401 });

  const body = await request.json();
  const id = body?.id;
  if (!id) return new Response("Missing id", { status: 400 });
  await prisma.discountCode.delete({ where: { id } as any });
  return new Response(null, { status: 204 });
}
