/* eslint-disable @typescript-eslint/no-explicit-any */
// THIS FILE IS AUTO-GENERATED. DO NOT EDIT MANUALLY.
// Generated by prismagen

import { prisma } from "@/prisma/prisma";

// NOTE: Thin DB wrappers. Add business logic/validation/select/include as needed.

export async function UserDiscountCode_GetAll() {
  return prisma.userDiscountCode.findMany();
}
export type UserDiscountCode_GetAll = Awaited<ReturnType<typeof UserDiscountCode_GetAll>>;

export async function UserDiscountCode_GetById(id: string) {
  const item = await prisma.userDiscountCode.findUnique({
    where: { id } as any,
    include: {
      discountCode: true,
      transactions: true,
      user: true,
    },
  });

  if (!item) {
    throw new Error("UserDiscountCode not found");
  }
  return item;
}
export type UserDiscountCode_GetById = Awaited<ReturnType<typeof UserDiscountCode_GetById>>;

export async function UserDiscountCode_Create(data: any) {
  return prisma.userDiscountCode.create({ data });
}
export type UserDiscountCode_Create = Awaited<ReturnType<typeof UserDiscountCode_Create>>;

export async function UserDiscountCode_Update(id: string, data: any) {
  return prisma.userDiscountCode.update({ where: { id } as any, data });
}
export type UserDiscountCode_Update = Awaited<ReturnType<typeof UserDiscountCode_Update>>;

export async function UserDiscountCode_Delete(id: string) {
  return prisma.userDiscountCode.delete({ where: { id } as any });
}
export type UserDiscountCode_Delete = Awaited<ReturnType<typeof UserDiscountCode_Delete>>;
