/* eslint-disable @typescript-eslint/no-explicit-any */
// THIS FILE IS AUTO-GENERATED. DO NOT EDIT MANUALLY.
// Generated by prismagen

import { prisma } from "@/prisma/prisma";

// NOTE: Thin DB wrappers. Add business logic/validation/select/include as needed.

export async function DiscountCode_GetAll() {
  return prisma.discountCode.findMany();
}
export type DiscountCode_GetAll = Awaited<ReturnType<typeof DiscountCode_GetAll>>;

export async function DiscountCode_GetById(id: string) {
  const item = await prisma.discountCode.findUnique({
    where: { id } as any,
    include: {
      userDiscountCodes: true,
    },
  });

  if (!item) {
    throw new Error("DiscountCode not found");
  }
  return item;
}
export type DiscountCode_GetById = Awaited<ReturnType<typeof DiscountCode_GetById>>;

export async function DiscountCode_Create(data: any) {
  return prisma.discountCode.create({ data });
}
export type DiscountCode_Create = Awaited<ReturnType<typeof DiscountCode_Create>>;

export async function DiscountCode_Update(id: string, data: any) {
  return prisma.discountCode.update({ where: { id } as any, data });
}
export type DiscountCode_Update = Awaited<ReturnType<typeof DiscountCode_Update>>;

export async function DiscountCode_Delete(id: string) {
  return prisma.discountCode.delete({ where: { id } as any });
}
export type DiscountCode_Delete = Awaited<ReturnType<typeof DiscountCode_Delete>>;
